### PR TITLE
Fix 25 issue

### PR DESCRIPTION
**Pull request by syohex**
This is related to #25.
CC: @MaksVal,  @joaoalf Could you try this PR version ?

### CODE REVIEW

**Comment by joaoalf** [comment]
@syohex I tried your PR and it works. Thanks!

:+1:

**Comment by gongo** [comment]
@syohex Thanks for PR !!

@MaksVal @joaoalf Sorry for the delay in my response 🙇

**Comment by NTC-Vulkan** [comment]
Hi, gongo! Thanks for your fix! :)

I tryed to check it, but I have trouble with connect to server.
`OrgRedmine - Not retrieved: Can't find issue #5094 on https://url-redmine.com/`
I know what that https://url-redmine.com/issue/5094.json and my API key is working. I checked it in emacs-w3m. 

Do you can help me? How I can debug it?
Thanks!!
 Sorry for the delay in my response

**Comment by MaksVal** [comment]
Hi, gongo! Thanks for your fix! :)

I tryed to check it, but I have trouble with connect to server.
`OrgRedmine - Not retrieved: Can't find issue #5094 on https://url-redmine.com/`
I know what that https://url-redmine.com/issue/5094.json and my API key is working. I checked it in emacs-w3m. 

Do you can help me? How I can debug it?
Thanks!!
 Sorry for the delay in my response.

**Comment by gongo** [comment]
Hi @MaksVal 

Thank you for comment. But please create new issue about this problem. 🙇

**Pull request merged**
